### ISSUE TITLE
Lightning address is empty in /help

### ISSUE THREAD

**Issue by ChuckNorrison** [LightningTipBot/LightningTipBot#428]
The bot works as expected, but at help command, the lightning addresses displayed are incomplete. The `@domain` is missing. 

> ℹ️ Info
> Your Lightning address is user@

Already updated the config, but as described (https://github.com/LightningTipBot/LightningTipBot#lnurl-server), there is no config `lnurl_public_server`. 

my config looks like this:
```
bot:
  socks_proxy:
      host: 127.0.0.1:9996
      username: test
      password: username
  tor_proxy:
      host: 127.0.0.1:9050
  http_proxy: ""
  lnurl_public_host_name: "mydomain.org"
  lnurl_server: "https://mydomain.org/lndhub/ext"
  lnurl_image: true
  admin_api_host: localhost:6060
telegram:
  message_dispose_duration: 10
  api_key: "1234:xyz"
lnbits:
  url: "http://127.0.0.1:5000"
  admin_key: "myadminkey"
  admin_id: "myadminid"
  webhook_server: "http://0.0.0.0:5588"
  lnbits_public_url: "https://mydomain.org"
database:
  db_path: "data/bot.db"
  buntdb_path: "data/bunt.db"
  transactions_path: "data/transactions.db"
  shop_buntdb_path: "data/shop.db"
  groupsdb_path: "data/groups.db"
generate:
  dalle_key: "asd"
  dalle_price: 1000
  worker: 2
```

How can i fix the displayed lightning addresses?
